CREATE ROLE IF NOT EXISTS BIDPILOT_READER;
CREATE ROLE IF NOT EXISTS BIDPILOT_RUNNER;

GRANT USAGE ON WAREHOUSE BIDPILOT_WH TO ROLE BIDPILOT_READER;
GRANT USAGE ON DATABASE BIDPILOT_DEMO TO ROLE BIDPILOT_READER;
GRANT USAGE ON SCHEMA BIDPILOT_DEMO.BIDPILOT TO ROLE BIDPILOT_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA BIDPILOT_DEMO.BIDPILOT TO ROLE BIDPILOT_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA BIDPILOT_DEMO.BIDPILOT TO ROLE BIDPILOT_READER;

GRANT USAGE ON WAREHOUSE BIDPILOT_WH TO ROLE BIDPILOT_RUNNER;
GRANT USAGE ON DATABASE BIDPILOT_DEMO TO ROLE BIDPILOT_RUNNER;
GRANT USAGE ON SCHEMA BIDPILOT_DEMO.BIDPILOT TO ROLE BIDPILOT_RUNNER;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA BIDPILOT_DEMO.BIDPILOT TO ROLE BIDPILOT_RUNNER;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA BIDPILOT_DEMO.BIDPILOT TO ROLE BIDPILOT_RUNNER;

-- Account administrators grant these roles to the authenticated app and runner users.
