-- Apply with ACCOUNTADMIN. Revoke the earlier schema-wide grants first so the
-- named connections stay least-privilege even after upgrading an existing demo.
CREATE ROLE IF NOT EXISTS BIDPILOT_READER;
CREATE ROLE IF NOT EXISTS BIDPILOT_RUNNER;

REVOKE SELECT ON FUTURE TABLES IN SCHEMA BIDPILOT_DEMO.BIDPILOT FROM ROLE BIDPILOT_READER;
REVOKE SELECT ON ALL TABLES IN SCHEMA BIDPILOT_DEMO.BIDPILOT FROM ROLE BIDPILOT_READER;

REVOKE SELECT, INSERT, UPDATE ON FUTURE TABLES IN SCHEMA BIDPILOT_DEMO.BIDPILOT FROM ROLE BIDPILOT_RUNNER;
REVOKE SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA BIDPILOT_DEMO.BIDPILOT FROM ROLE BIDPILOT_RUNNER;

GRANT USAGE ON WAREHOUSE BIDPILOT_WH TO ROLE BIDPILOT_READER;
GRANT USAGE ON DATABASE BIDPILOT_DEMO TO ROLE BIDPILOT_READER;
GRANT USAGE ON SCHEMA BIDPILOT_DEMO.BIDPILOT TO ROLE BIDPILOT_READER;

-- The Streamlit reader only reloads the run and the records rendered by it.
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.AGENT_RUNS TO ROLE BIDPILOT_READER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.OPPORTUNITIES TO ROLE BIDPILOT_READER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.SUPPLIER_PROFILES TO ROLE BIDPILOT_READER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.PURSUIT_DECISIONS TO ROLE BIDPILOT_READER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.WIN_STRATEGIES TO ROLE BIDPILOT_READER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.RUBRIC_RESPONSE_PLANS TO ROLE BIDPILOT_READER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.PROPOSAL_SECTIONS TO ROLE BIDPILOT_READER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.PURSUIT_TASKS TO ROLE BIDPILOT_READER;

GRANT USAGE ON WAREHOUSE BIDPILOT_WH TO ROLE BIDPILOT_RUNNER;
GRANT USAGE ON DATABASE BIDPILOT_DEMO TO ROLE BIDPILOT_RUNNER;
GRANT USAGE ON SCHEMA BIDPILOT_DEMO.BIDPILOT TO ROLE BIDPILOT_RUNNER;

-- Source and supplier-memory tables are immutable inputs for the runner.
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.OPPORTUNITIES TO ROLE BIDPILOT_RUNNER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.OPPORTUNITY_DOCUMENTS TO ROLE BIDPILOT_RUNNER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.REQUIREMENTS TO ROLE BIDPILOT_RUNNER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.EVALUATION_CRITERIA TO ROLE BIDPILOT_RUNNER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.SUBMISSION_ITEMS TO ROLE BIDPILOT_RUNNER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.SUPPLIER_PROFILES TO ROLE BIDPILOT_RUNNER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.CREDENTIALS TO ROLE BIDPILOT_RUNNER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.PEOPLE TO ROLE BIDPILOT_RUNNER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.AVAILABILITY TO ROLE BIDPILOT_RUNNER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.PAST_PROJECTS TO ROLE BIDPILOT_RUNNER;
GRANT SELECT ON TABLE BIDPILOT_DEMO.BIDPILOT.PAST_PROPOSALS TO ROLE BIDPILOT_RUNNER;

-- Derived artifacts are append-only. Only AGENT_RUNS permits lifecycle updates.
GRANT SELECT, INSERT ON TABLE BIDPILOT_DEMO.BIDPILOT.PURSUIT_DECISIONS TO ROLE BIDPILOT_RUNNER;
GRANT SELECT, INSERT ON TABLE BIDPILOT_DEMO.BIDPILOT.WIN_STRATEGIES TO ROLE BIDPILOT_RUNNER;
GRANT SELECT, INSERT ON TABLE BIDPILOT_DEMO.BIDPILOT.RUBRIC_RESPONSE_PLANS TO ROLE BIDPILOT_RUNNER;
GRANT SELECT, INSERT ON TABLE BIDPILOT_DEMO.BIDPILOT.PROPOSAL_SECTIONS TO ROLE BIDPILOT_RUNNER;
GRANT SELECT, INSERT ON TABLE BIDPILOT_DEMO.BIDPILOT.PURSUIT_TASKS TO ROLE BIDPILOT_RUNNER;
GRANT SELECT, INSERT, UPDATE ON TABLE BIDPILOT_DEMO.BIDPILOT.AGENT_RUNS TO ROLE BIDPILOT_RUNNER;

-- Bound demo compute. Account administrators may deliberately adjust the quota,
-- but the repository default is finite and suspends immediately at exhaustion.
CREATE RESOURCE MONITOR IF NOT EXISTS BIDPILOT_COST_MONITOR
  WITH CREDIT_QUOTA = 5
       FREQUENCY = MONTHLY
       START_TIMESTAMP = IMMEDIATELY
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER RESOURCE MONITOR BIDPILOT_COST_MONITOR
  SET CREDIT_QUOTA = 5
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE BIDPILOT_WH SET
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 300
  STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 60;
ALTER WAREHOUSE BIDPILOT_WH SET RESOURCE_MONITOR = BIDPILOT_COST_MONITOR;

-- Account administrators separately grant these roles to the intended user.
